# Generated by Django 2.0 on 2017-12-27 07:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='created_with',
        ),
        migrations.AddField(
            model_name='conversation',
            name='creator_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='conversation',
            name='subscriber',
            field=models.ManyToManyField(related_name='conversation', to=settings.AUTH_USER_MODEL),
        ),
    ]
