# Generated by Django 2.0 on 2017-12-27 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20171227_0756'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='is_archive',
            new_name='is_archived',
        ),
    ]
