# Generated by Django 2.0 on 2017-12-28 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20171227_0805'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='owner',
            new_name='sender',
        ),
    ]
