# Generated by Django 2.0 on 2017-12-28 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20171228_0730'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_marked_read',
            field=models.BooleanField(default=False),
        ),
    ]
