# Generated by Django 2.0 on 2017-12-27 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='already_set_password',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='email_verified',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='nick_name',
        ),
    ]
